volumes:
  pg_data:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  backend:
    build: ./my_site/
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy